# .github/workflows/docker-publish.yml

name: Docker Build and Push

on:
  push:
    branches: [ main ] # 当推送到 main 分支时触发

env:
  DOCKER_HUB_USERNAME: safiindeed # 替换为你的 Docker Hub 用户名
  IMAGE_NAME: myinstantidworkflows # 替换为你的镜像名称

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 120 # 设置作业的超时时间为 120 分钟

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        cache-from: type=registry,ref=${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        cache-to: type=inline
